### ISSUE TITLE
Autotune makes my code benchmark execute slower

### ISSUE THREAD

**Issue by MisakiTakeru** [diku-dk/futhark#1554] opened 2021-12-22 15:27 UTC
Hi

I have run this with benchmark opencl both before and after using autotune, and on gpu03 I have noticed the general execution has slowed down after using autotune.

```
let argmax arr =
  reduce_comm (\(a,i) (b,j) ->
                 if a < b
                 then (b,j)
                 else if b < a then (a,i)
                 else if j < i then (b,j)
                 else (a,i))
              (0f32, 0)
              (zip arr (indices arr))

let gaussian_elimination [n] [m] (A: [m][n]f32): [m][n]f32 =
  loop A for i < i64.min m n do
    -- Find nonzero pivot.
    -- Written carefully to avoid irregular parallelism.
    let value j x = if j >= i then f32.abs x else -f32.inf
    let j = A[:,i] |> map2 value (indices A) |> argmax |> (.1)
    let f = (1-A[i,i]) / A[j,i]
    let irow = map2 (f32.fma f) A[j] A[i]
    in tabulate m (\j ->
                     let f = A[j,i] * -1
                     in map2 (\x y -> if j == i then x else f32.fma f x y)
                             irow A[j])

let matrix_inverse [n] (A: [n][n]f32): [n][n]f32 =
  let n2        = n + n
  let augmented = map (\ i1 -> 
                    map (\ i2 -> 
                      if i1+n == i2
                      then 1f32
                      else if i2 < n
                           then A[i1,i2]
                           else 0f32) 
                              (iota n2 )) 
                                (iota n)
  let changed = gaussian_elimination augmented
  let inverse = map (\arr -> take n (reverse arr) |> reverse) changed
  in inverse


let main [k][n] (A: [k][n][n]f32): [k][n][n]f32 =
  map (\mat -> matrix_inverse mat) A


entry test_main = main
--
--
-- ==
-- entry: test_main
-- random input { [100000][2][2]f32 }
-- random input { [100000][4][4]f32 }
-- random input { [100000][6][6]f32 }
-- random input { [100000][8][8]f32 }
-- random input { [100000][10][10]f32 }
-- random input { [100000][12][12]f32 }
-- random input { [100000][14][14]f32 }
-- random input { [100000][16][16]f32 } 
```

**Comment by athas** [comment] 2021-12-22 15:51
I cannot reproduce.  Could you show the before/after benchmark results?

**Comment by athas** [comment] 2021-12-22 15:54
Oh, I can reproduce with the `opencl` backend, but not `cuda`.  Interesting.

**Comment by Munksgaard** [comment] 2021-12-29 14:38
It looks like there's some non-monotonicity in the generated program. The only datasets necessary to exhibit the issue are the `[100000][8][8]f32` and `[100000][16][16]f32` inputs. Here's a log that illustrates the problem:

```
[jxk588@gpu03:~/src/futhark]$ cat ~/tmp/data/\[100000\]\[8\]\[8\]f32.in | ~/tmp/foo --param main.suff_outer_par_0=2000000000 --param main.suff_intra_par_1=2000000000 --param main.suff_outer_par_2=2000000000 --param=main.suff_intra_par_3=2000000000 -r 1 -t /dev/stderr > /dev/null
19487

[jxk588@gpu03:~/src/futhark]$ cat ~/tmp/data/\[100000\]\[8\]\[8\]f32.in | ~/tmp/foo --param main.suff_outer_par_0=2000000000 --param main.suff_intra_par_1=1 --param main.suff_outer_par_2=2000000000 --param=main.suff_intra_par_3=2000000000 -r 1 -t /dev/stderr > /dev/null
17260

[jxk588@gpu03:~/src/futhark]$ cat ~/tmp/data/\[100000\]\[16\]\[16\]f32.in | ~/tmp/foo --param main.suff_outer_par_0=2000000000 --param main.suff_intra_par_1=20000000 --param main.suff_outer_par_2=2000000000 --param=main.suff_intra_par_3=2000000000 -r 1 -t /dev/stderr > /dev/null
112319

[jxk588@gpu03:~/src/futhark]$ cat ~/tmp/data/\[100000\]\[16\]\[16\]f32.in | ~/tmp/foo --param main.suff_outer_par_0=2000000000 --param main.suff_intra_par_1=1 --param main.suff_outer_par_2=2000000000 --param=main.suff_intra_par_3=2000000000 -r 1 -t /dev/stderr > /dev/null
154790
```

In short, the intragroup version is optimal for the input with block size 8, while the fully flattened version is optimal for the input with block size 16. Unfortunately, that is not expressible using our current tuning method: When tuning on the dataset with block size 8 and the intragroup version is found to be optimal, it is assumed that the intragroup version will also be optimal for all datasets with a larger block size.

I don't think there's a good fix for this at the moment. We need to be able to produce the tuning tree in a different ordering, but it's not straightforward to know how and when to do that.

**Comment by athas** [comment] 2021-12-29 14:41
Can we at least detect this and print a warning?

**Closed** 2022-01-03 16:01 UTC
