### ISSUE TITLE
Coercing size seems to be broken in the last version

### ISSUE THREAD

**Issue by baptistecdr** [diku-dk/futhark#1531] opened 2021-11-21 16:09 UTC
Hello,

I try to compile my project on the last version of Futhark (0.20.6) but It fail. It was working fine on 0.19.7.

```
type~ side_envelope_3d_t = {
    east: [][][]u8,       -- edge
    north: [][][]u8,      -- edge
    north_east: [][][]u8, -- vertices
    north_west: [][][]u8, -- vertices
    south: [][][]u8,      -- edge
    south_east: [][][]u8, -- vertices
    south_west: [][][]u8, -- vertices
    surface: [][][]u8,
    west: [][][]u8        -- edge
}

type~ envelope_3d_t = {
    back: side_envelope_3d_t,
    bottom: side_envelope_3d_t,
    front: side_envelope_3d_t,
    left: side_envelope_3d_t,
    right: side_envelope_3d_t,
    top: side_envelope_3d_t
}

entry get_envelope_3d [n][m][l] (cube:[n][m][l]u8) (thickness_y: i64) (thickness_x: i64) (thickness_z: i64): envelope_3d_t =
    -- ...
    let bottom = {
        north_west = cube[n - thickness_y:, 0:thickness_x, l-thickness_z:] :> [thickness_y][thickness_x][thickness_z]u8,
        west = cube[n-thickness_y:, 0:thickness_x, :] :> [thickness_y][thickness_x][l]u8,
        south_west = cube[n - thickness_y:, 0:thickness_x, 0:thickness_z] :> [thickness_y][thickness_x][thickness_z]u8,
        south = cube[n-thickness_y:, :, 0:thickness_z] :> [thickness_y][m][thickness_z]u8,
        south_east = cube[n - thickness_y:n, m - thickness_x:, 0:thickness_z] :> [thickness_y][thickness_x][thickness_z]u8,
        east = cube[n-thickness_y:, m-thickness_x:, :] :> [thickness_y][thickness_x][l]u8,
        north_east = cube[n - thickness_y:, m - thickness_x:, l-thickness_z:] :> [thickness_y][thickness_x][thickness_z]u8,
        north = cube[n-thickness_y:, :, l-thickness_z:] :> [thickness_y][m][thickness_z]u8,
        surface = cube[n-thickness_y:, :, :] :> [thickness_y][m][l]u8
    }
    -- ...
    in { back, bottom, front, left, right, top }
```

When I compile, I have the error :

> Dimensions "n" and "thickness_y" do not match.
> When matching types of record field "**bottom.east**".

It doesn't seem right, the size should be `thickness_y` because if **n** is 10 and **thickness_y** is 1, well, I will have one cell in Y dimension.

So, let's trust the compiler and fixed it by **n** and compile.

> Dimensions "thickness_z" and "l" do not match.
> When matching types of record field "**bottom.east**".

Hum, I take all the cells in Z dimension, so why expecting a `thickness_z` size ?

It's keep complaining about the coercing size for each field (bottom.east, bottom.surface, etc.).

**Comment by athas** [comment] 2021-11-22 22:30
It's a bit hard to tell what is going on from the program fragment you posted.  I don't even see why it would care about the size of `bottom.east` at all, since `envelope_3d_t` and `side_envelope_3d_t` imposes no constraints.  Are you sure you're not doing something else in the function that is imposing constraints?

**Comment by athas** [comment] 2021-11-22 22:33
There was one subtle size type checking bug fixed in 0.20.1 (#1435), which may why it used to type check.  But what you have shown me of the program would not have interacted with that bug.

**Comment by baptistecdr** [comment] 2021-11-24 19:31
Thank you for the fast response.

Unfortunately, even if I ditch the coercing size, it won't compile.

> Dimensions "n" and "n₂₀" do not match.
> When matching types of record field "bottom.east".
> 
> Note: "n₂₀" is size produced by slice
>         n - thickness_y:
>       of dimension of size "n" at 63:22-73.

I uploaded the file and I try to compile with `futhark c envelope.fut`.

Something weird is, if I keep only one field in `envelope_3d_t` and modify `get_envelope_3d` to return that field, It compiles. With two fields or more, the compiler complains about the dimensions.

[envelope.txt](https://github.com/diku-dk/futhark/files/7598243/envelope.txt)

**Comment by athas** [comment] 2021-11-24 20:46
Interesting!  It's not size coercion that is broken; instead it appears to be in the elaboration of types.  This is probably a regression caused by the addition of existential sizes.  Here is a simple program that illustrates the problem:

```
type~ t0 = ([]i64, []i64)

type~ t1 = (t0, t0)

let main: t1 =
  let a = (iota 1, iota 2)
  let b = (iota 3, iota 4)
  in (a, b)
```

The first thing to understand is that the `t0` type abbreviation is actually shorthand for this:

```
type~ t0	= ?[n][m].([n]i64, [m]i64)
```

That is, it contains some hidden inner sizes.  The problem is that when it is substituted in `t1`, the result *should* be this:

```
type~ t1	= (?[n][m].([n]i64, [m]i64), ?[n][m].([n]i64, [m]i64))
```

But it *actually* becomes this:

```
type~ t1	= ?[n][m].(([n]i64, [m]i64), ([n]i64, [m]i64))
```

That is, the two instances of `t0` must have the same size.  In the original program, it means all of the `side_envelope_3d_t` values in `envelope_3d_t` must have the same size.

This is a bug in the type checker and it will be fixed.  The workaround is to inline the type definitions (or give them proper size parameters), which is unfortunately impractically verbose for this program.

**Closed** 2021-11-25 19:48 UTC
Labels: bug, compiler
