### ISSUE TITLE
Failed to allocate memory on certain input sizes

### ISSUE THREAD

**Issue by nbos** [diku-dk/futhark#1797] opened 2022-12-13 21:55 UTC
The program
```
entry main (n: i64) : f32 =                                                                                                                                    
  let xs = replicate 256 1                                                                                                                                     
  let ys = tabulate 48000 (\i -> replicate 2 xs[i])                                                                                                            
  let f i = f32.sum (map (\y -> xs[i] * f32.sum y) ys)                                                                                                         
  in f32.sum (tabulate n f)
```
compiled with backend `opencl` runs fine with large inputs (from `n > 1000000` down to `n = 33000`), but for `n = 32000` down to `n = 11000` it attempts to allocate more than what is available on the device, printing the following:
```
 echo 32000 | ./test
./test: Failed to allocate memory in space 'device'.
Attempted allocation:   6144000000 bytes
Currently allocated:             0 bytes
test.c:7770: OpenCL call
  opencl_alloc(&ctx->opencl, ctx->log, (size_t) size, desc, &block->mem)
failed with error code -4 (Memory object allocation failure)
```
which is a 6GB allocation while using a GTX 770 that has 2GB of memory.

**Comment by athas** [comment] 2022-12-14 08:33
This is strictly speaking not a bug, but a result of fully flattened code being memory-inefficient.  The reason this happens only for mid-sized workloads is that incremental flattening will only pick the fully flattened version when the amount of top-level parallelism is insufficient (i.e. when `n` is too small).  If the thresholds are autotuned, the versions that run out of memory will be marked as having infinite runtime, and so will never be picked.  Another workaround is explicitly mark the inner sum with a `#[sequential]` attribute if you know you will never need its parallelism.

Unfortunately it is not viable to check memory requirements and availability at run-time, before picking between code versions, because it is in general not possible to know how much memory is available, nor how much we need.  (The latter can be known for this *specific* program, but not in general, and capacity is never known on a shared system.)

**Closed as completed** 2022-12-14 17:58 UTC
