### ISSUE TITLE
Compiler Interpreter Discrepancy Example #2

### ISSUE THREAD

**Issue by capt-glorypants** [diku-dk/futhark#1755] opened 2022-11-03 16:49 UTC
With the files 2.fut (renamed because GitHub doesn't accept .fut):
[2.txt](https://github.com/diku-dk/futhark/files/9931322/2.txt)

And games.fut (again renamed):
[games.txt](https://github.com/diku-dk/futhark/files/9931323/games.txt)

If I run the command "futhark opencl 2.fut && echo "" | ./2 && echo "-----" && echo "" | futhark run 2.fut" with Futhark 0.22.0, I get the output:
```
[43u8, 53u8]
507.000000f64
33i64
-----
[43u8, 53u8]
1.0f64
33i64
```
The command first compiles and run the compiled program, and then runs the same program with the interpreter. The program is a minimax implementation of a game where the game state is just a number. The three lines it outputs are the best move, the evaluation, and the number of leaves in the move tree. We can see that it finds two different evaluations for the same program. The evaluation of 1 is the correct one.

**Comment by athas** [comment] 2022-11-06 09:35
I can reproduce and `oclgrind` shows some memory errors in scalar GPU code.

**Comment by athas** [comment] 2022-11-06 09:52
The problem is somehow caused by scalar migration (although it might be due to subsequent simplifications).

**Comment by athas** [comment] 2022-11-06 14:17
Those memory errors, while real enough, did not affect the actual computed score.

This is actually a bug in memory memory block merging, where two blocks that are concurrently live are incorrectly merged.

Debugging this one sucked.

**Closed** 2022-11-06 14:38 UTC
Labels: bug, compiler
