### ISSUE TITLE
Error after in-place lowering

### ISSUE THREAD

**Issue by maedoc** [diku-dk/futhark#1460] opened 2021-09-07 13:44 UTC
I am using Futhark as follows,
```
$ futhark -V
Futhark 0.21.0
git: 42be3a2 (Fri Sep 3 21:48:38 2021 +0200) [modified]
```
(I think the modified is because I switch to lts-18 in the stack.yml? I can recompile if that's a worry)
with the program
```futhark
let update [n] [m] (mat: *[n][m]i64): *[n][m]i64 =
    let mat = rotate (-1) mat
    in mat with [n-1] = iota m

let run (t:i64) (n:i64) (m:i64): [n][m]i64 =
    let mat = tabulate_2d n m (+) in
    loop (mat) for i < t do update mat

-- ==
-- input { 1000i64 2560i64 400i64 } 
let main (t:i64) (n:i64) (m:i64) =
    map (\i -> run t n m) (iota 10)
```
called with `futhark bench membrr.fut`, with the result
```
Compiling membrr.fut...
Compilation of membrr.fut failed:

Warning at membrr.fut:17:20-20:
  Unused variable "i" .

Warning at membrr.fut:22:11-11:
  Unused variable "i" .
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
Type error after pass 'In-place lowering':
In function entry_main
When checking function body
In expression of statement
  {defunc_3_map_res_5251 : ({}, [10i64][n_5233][m_5234]i64)}
Inside the loop body
In expression of statement
  {lw_dest_5273 : ({}, [10i64][n_5233][m_5234]i64)}
Inside the loop body
Type error:
Variable lowered_array_5279 referenced after being consumed.
```
There's almost surely something wrong with the code of course, but thanks for looking

**Comment by Munksgaard** [comment] 2021-09-07 13:46
I'm not getting the ICE on the latest master. Can you try to recompile?

**Comment by athas** [comment] 2021-09-07 13:48
This might be a duplicate of #1457.

**Comment by athas** [comment] 2021-09-07 13:49
No, it fails for me with the `c` backend, so it's a fresh (although related) bug.

**Comment by Munksgaard** [comment] 2021-09-07 13:57
Ah yes! I tried with the opencl backend, but the c backend fails for me too.

**Comment by maedoc** [comment] 2021-09-07 14:00
I noticed removing the `let mat = rotate (-1) mat in` allows the compilation to succeed.  I have no idea why but maybe this helps.

**Closed** 2021-09-07 14:59 UTC
