### ISSUE TITLE
Delete key does not work in REPL

### ISSUE THREAD

**Issue by dcz-self** [diku-dk/futhark#2079] opened 2024-01-09 15:19 UTC
Release Version 0.25.9.

To reproduce:

1. Run REPL
2. Type "1"
3. Press left arrow
4. Press Delete

Expected result: "1" is gone.

Actual result: terminal rings a bell.

I'm not sure if this is intentional, but I haven't seen it outside of misbehaving programs before.

**Comment by athas** [comment] 2024-01-09 15:31
I will see if I can reproduce (my keyboard does not have a Del key; I use Ctrl-d), but since Futhark just uses [haskeline](https://hackage.haskell.org/package/haskeline), we can't do much about misbehaviour.

**Comment by athas** [comment] 2024-01-09 17:36
Works on my machine.

**Comment by athas** [comment] 2024-01-10 13:04
I am going to close this because I cannot reproduce the problem, and if/when there is a problem, the fault is likely with haskeline.

**Closed by athas** 2024-01-10 13:04 UTC
