### ISSUE TITLE
Incorrect type inference using module type ascription

### ISSUE THREAD

**Issue by jarble** [diku-dk/futhark#1155] opened 2020-10-09 17:08 UTC
When using module type ascription, the types of parameters in a function are not always inferred consistently. Here, the parameter types in the `add` function are inferred to be `i32` instead of `f32`, so the program will not compile:

```
module type Addable = {
	type t
	val add: t -> t -> t
}
module Add_f32:Addable = {
	type t = f32
	let add a b = a + b
}
```
This program will compile if I add more type annotations, but this seems redundant, since the parameter types of `add` are already defined in the module type:
```
module type Addable = {
	type t
	val add: t -> t -> t
}
module Add_f32:Addable = {
	type t = f32
	let add (a:t) (b:t) = a + b
}
```
Is it possible for the compiler to infer these types consistently, without requiring redundant type annotations?

**Comment by athas** [comment] 2020-10-09 17:53
I'm afraid not.  This is a weakness that is shared with any language that has an ML-style module system (that I know of, anyway).  The issue is that the module ascription is conceptually and technically completely independent of type-checking at the term level.  A module must be fully type-checked (including resolving overloading, which is what happens here) before it can be matched against a module type.

As with #1153, I do think it's a problem that you are not told about the overloading if an error occurs.

**Closed** 2020-10-09 20:12 UTC
