### ISSUE TITLE
OpenCL: Memory leak: `futhark_context_free` doesn't free the context

### ISSUE THREAD

**Issue by nbos** [diku-dk/futhark#1676] opened 2022-05-10 22:15 UTC
Repeatedly calling Futhark functions eventually results in the error:
```
(embedded Futhark): fut/test.c:4290: OpenCL call
  clCreateContext_error
failed with error code -6 (Out of host memory)
```
Monitoring the on-card memory, I notice that the first call to `futhark_context_new` uses up 40MiB and that `futhark_context_free` has no effect on memory usage. Successive context allocations add about 37MiB each time and the memory doesn't clear until the card runs out of memory and the program crashes.

In that minimal example, the only functions I call are `futhark_context_config_new`, `futhark_context_new` and `futhark_context_free`. Is this normal behavior?

My environment:
- Hardware: GeForce GTX 770
- OS: Arch Linux
- Driver: `nvidia-470xx-dkms 470.103.01-1`
- OpenCL runtime: `opencl-nvidia-470xx 470.103.01-1`
- Futhark: `0.22.0` `git: 74ce47e` called with args `opencl --library`

**Comment by athas** [comment] 2022-05-11 04:06
Interesting.  I'm pretty sure this was fixed once, but we don't have any automated testing for this class of memory leaks, so I'm not surprised it has snuck back in.

**Comment by athas** [comment] 2022-05-11 04:15
What does the Futhark program do?  I cannot reproduce this on our NVIDIA system with a trivial Futhark program.

**Comment by athas** [comment] 2022-05-11 04:19
Also, which CUDA version are you using?  It's perfectly possible that this is actually an NVIDIA bug.  I doubt they test their OpenCL cleanup code well either.

**Comment by nbos** [comment] 2022-05-11 04:32
`cuda 10.2.89-5` which is the latest that supported my card, but why would CUDA be involved when it's compiled with the OpenCL backend?

**Comment by athas** [comment] 2022-05-11 04:34
NVIDIAs OpenCL implementation is part of the CUDA toolkit.

**Comment by athas** [comment] 2022-05-11 04:35
I will try to see if I can dig up a CUDA 10 system.  Just to ensure we're looking at the same thing, can you provide the Futhark and C program that you see this issue on?

**Comment by nbos** [comment] 2022-05-11 04:40
I reduced the functions to just constants and the problem is gone. I'll try to find a minimal example.

**Comment by nbos** [comment] 2022-05-11 05:00
I removed the `cuda` package and everything runs correctly (except for the leak). The only other trace of CUDA I can find is `nvidia-smi` reporting `CUDA Version: 11.4` but I don't know what that refers to.

I'm essentially only running with: 
- `nvidia-470xx-dkms 470.103.01-1` (driver)
- `opencl-nvidia-470xx 470.103.01-1` (opencl runtime)
- `opencl-headers 2:2022.01.04-1`
- `nvidia-470xx-utils 470.103.01-1`

**Comment by athas** [comment] 2022-05-11 05:13
I have the same CUDA version.  Could you provide the Futhark program so I can reproduce the issue?

**Comment by nbos** [comment] 2022-05-11 05:29
```
let cond 'a (g: bool) ((b0,b1): (a,a)) : a =
  if g then b0 else b1
let inside (i: f32) ((lo,up): (f32,f32)) : bool =
  lo <= i && i <= up
let compact_2d [n] [m] 'a (keep: [n][m]bool) (as: [n][m]a) : []a =
  map2 zip keep as |> flatten |> filter (.0) |> map (.1)
let fromPoints [d] (p0: [d]f32) (p1: [d]f32) : [d](f32,f32) =
    map2 (\i j -> if i < j then (i,j) else (j,i)) p0 p1

entry neighborsOf [m] [n] [d] (sl: [m][d]f32) (ps: [n][d]f32) : ([]i64,[]i64) =
  let cuboids = map (\s ->
		       map (fromPoints s) ps)
		    sl                              : [m][n][d](f32,f32)
  let vacant = map
	       (map (\bs ->
		       map (\pt ->
			      map2 inside pt bs
			      |> and |> flip cond (1,0))
			   (ps ++ sl) |> i32.sum |> (== 2)))
	       cuboids                              : [m][n]bool
  let tab2d = tabulate_2d m n (\j i -> (j,i))       : [m][n]((i64,i64))
  in compact_2d vacant tab2d |> unzip
```

**Comment by athas** [comment] 2022-05-11 05:32
I am using this C program:

```C
#include "test.h"

int main() {
  struct futhark_context_config *cfg = futhark_context_config_new();

  int i = 0;
  while (1) {
    printf("%d\n", i++);
    struct futhark_context *ctx = futhark_context_new(cfg);
    futhark_context_free(ctx);
  }

  futhark_context_config_free(cfg);
}
```

It does not appear to look memory on my machine.

**Comment by athas** [comment] 2022-05-11 05:35
Oh, but it might actually do so on the NVIDIA systems...

**Comment by athas** [comment] 2022-05-11 05:37
I can reproduce the leak when using the CUDA backend, but not the OpenCL backend.  That is quite unexpected.

**Comment by athas** [comment] 2022-05-11 05:41
I see it.  We're neglecting to deallocate some of the utility arrays used for bookkeeping during reductions and such.

**Closed** 2022-05-11 05:57 UTC
