### ISSUE TITLE
Internal compiler error for opencl and cuda backends

### ISSUE THREAD

**Issue by Traffelaffen** [diku-dk/futhark#1424] opened 2021-08-04 09:55 UTC
I've run into an internal compiler error, and reporting it as suggested by the compiler.

The gutted code snippet below reproduces the error when compiled using the cuda and opencl backends, but seems to work fine with the c and multicore backends.

Additionally setting #[unroll]  on the first loop (line 19) seems to resolve the error.

```
type index  = {x: i64, y: i64, z: i64}
type weight = f64

let prolongateCell (c :index, w :weight) =
  replicate 4 (c,w)

let getFineValue (o :i64) (cellIndex :index, w :weight) :[24]f64 =
  replicate 24 0f64

let restrictCell (vals :[4][24]f64) :[24]f64 =
  vals |> transpose |> map (\x -> reduce (+) 0 x)


let getCoarseCellContribution (cellIndex :index, w :weight) =
  let l = 2 -- compilation fails when l > 1

  -- recursively multiplies the number of elements by 8 for (l-1) times
  let fineCells =
    loop vals = [(cellIndex,w)] for i < (i64.u8 l) do
      vals |> map prolongateCell |> flatten_to (4**(i+1))

  let fineValues = map (getFineValue 0) fineCells

  -- recursively gathers 8 elements into 1
  let coarseValues =
    loop v = fineValues for i < (i64.u8 l) do
      let ii = (i64.u8 l) - i - 1 -- flip indices
      in v |> unflatten (4**(ii)) 4 |> map restrictCell
  in flatten_to 24 coarseValues

let getDiagonalCellContribution (elementOffset :index) :[3]f64 =
  let weights :weight = 0
  let vals = getCoarseCellContribution (elementOffset, weights)
  in [vals[0],vals[0],vals[0]]

entry getNodeDiagonalValues () :[3]f64 =
  [{x=( 0),y=( 0),z=( 0)}, {x=(-1),y=( 0),z=( 0)}]
   |> map (getDiagonalCellContribution)
   |> transpose
   |> map (\x -> reduce (+) 0 x)
```

**Comment by athas** [comment] 2021-08-04 10:09
I cannot reproduce with the HEAD version of the compiler, so I think this will be fixed with the next release.  Could you try with the latest nightly? https://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz

**Comment by Traffelaffen** [comment] 2021-08-04 11:17
Of course, I was testing using 19.7. 

When using the nightly build the gutted example above works for me also, but the original version still gives an internal error. I've attached the original version in a .txt file. Sorry for the messy code, I was hoping to save you the trouble by gutting most of the noise out.
[error.txt](https://github.com/diku-dk/futhark/files/6930746/error.txt)

**Comment by athas** [comment] 2021-08-04 11:38
I can reproduce the issue.  I'll take a closer look.

**Comment by athas** [comment] 2021-08-04 14:09
Smaller reproducible example:

```
type index       = {x: i64, y: i64, z: i64}

let E    :f64 = 1
let Emin :f64 = 1e-6

let indexIsInside (nelx :i64, nely :i64, nelz :i64) (idx :index) :bool =
  (idx.x >= 0 && idx.y >= 0 && idx.z >= 0 && idx.x < nelx && idx.y < nely && idx.z < nelz)

let isOnBoundary(nodeIndex :index, nx :i64, ny :i64, nz :i64) :bool = (nodeIndex.x == 0)

type nodalWeights = (f64, f64)

-- utility methods for doing averages for the element edge, surface, and center
let sumEdge (a :f64, b :f64)                 = 0.5*(a+b)
let sumSurf (a :f64, b :f64, c :f64, d :f64) = 0.25*(a+b+c+d)
let sumCent (w :nodalWeights)                = 0.125*(w.0+w.1)

let prolongateCell (cellIndex :index, w :nodalWeights) =
  let i = cellIndex
  let c   = sumCent w
  let sxp = sumSurf (w.1,w.1,w.1,w.1)  -- Surface X positive
  let sxn = sumSurf (w.0,w.1,w.1,w.1)
  let syp = sumSurf (w.1,w.0,w.1,w.1)
  let syn = sumSurf (w.1,w.1,w.1,w.1)
  let szp = sumSurf (w.1,w.1,w.1,w.1)
  let szn = sumSurf (w.0,w.1,w.1,w.1)
  in [({x=(2*i.x+0),y=(2*i.y+1),z=(2*i.z+0)}, (w.0, sumEdge(w.0,w.1))),
      ({x=(2*i.x+1),y=(2*i.y+1),z=(2*i.z+0)}, (sumEdge(w.1,w.0), w.1))]

let generateLoad (o :i64) (w :nodalWeights) :[24]f64 =
  scatter (replicate 24 0) [0+o,3+o,6+o,9+o,12+o,15+o,18+o,21+o] [w.0, w.1, w.1, w.1, w.0, w.0, w.0, w.1]

let applyBoundaryConditionsToWeightsInverse (elementIndex :index, w :nodalWeights) (nx :i64, ny :i64, nz :i64) :nodalWeights =
  let ei = elementIndex
  let setIfNotIndex (v :f64) (nodeIndex :index) :f64 = if (isOnBoundary (nodeIndex,nx,ny,nz)) then (v/8) else 0
  in (setIfNotIndex w.0 {x=ei.x+0,y=ei.y+1,z=ei.z+0},
      setIfNotIndex w.1 {x=ei.x+1,y=ei.y+1,z=ei.z+0})

let getFineValue [nelx][nely][nelz] (x :[nelx][nely][nelz]f32) (o :i64) (cellIndex :index, w :nodalWeights) :[24]f64 =
  let w_onBoundary = applyBoundaryConditionsToWeightsInverse (cellIndex, w) ((nelx+1),(nely+1),(nelz+1))
  let loadVectorOnBoundary = generateLoad o w_onBoundary
  in loadVectorOnBoundary

let restrictCell (vals :[8][24]f64) :[24]f64 =
  vals |> transpose |> map (\x -> reduce (+) 0 x)

let getDiagonalCellContribution [nelx][nely][nelz] (l :u8) (x :[nelx][nely][nelz]f32) (cellIndex, w) =
  let fineCells =
    loop vals = [(cellIndex,w)] for i < (i64.u8 l) do
      vals |> map prolongateCell |> flatten_to (8**(i+1))
  let fineValuesX = map (getFineValue x 0) fineCells
  let coarseValues =
    loop vx = fineValuesX for i < (i64.u8 l) do
      let ii = (i64.u8 l) - i - 1
      let xx = vx |> unflatten (8**(ii)) 8 |> map restrictCell
      in xx
  let coarseX = flatten_to 24 coarseValues
  in coarseX

entry getNodeDiagonalValues [nelx][nely][nelz] (l :u8) (x :[nelx][nely][nelz]f32) input =
  map (getDiagonalCellContribution l x) input
```

Note that even with this fixed, this program is still likely to be rejected by the GPU backends, as the computation of fineCells and coarseValues involves irregular allocations in a loop.  Of course, if the unrolling actually worked, then it would be a loop anymore, but `l` isn't a constant, so it won't be able to unroll this.

I suggest keeping the loop parameter a one-dimensional array of fixed size and reshaping as needed inside the body.

**Comment by athas** [comment] 2021-08-04 14:13
An even smaller case:

```
let main n (xs: []i32) (unit: [1]i32) =
  #[sequential_inner]
  map (\x ->
         let arr = replicate 1 x
         in loop arr for i < n do
              unit)
      xs
```

**Closed** 2021-08-05 08:12 UTC
