### ISSUE TITLE
Compiler Interpreter Discrepancy Example #1

### ISSUE THREAD

**Issue by capt-glorypants** [diku-dk/futhark#1754] opened 2022-11-03 16:46 UTC
With the files 1.fut (renamed because GitHub doesn't accept .fut):
[1.txt](https://github.com/diku-dk/futhark/files/9931282/1.txt)

And games.fut (again renamed):
[games.txt](https://github.com/diku-dk/futhark/files/9931283/games.txt)

If I run the command "futhark opencl 1.fut && echo "" | ./1 && echo "-----" && echo "" | futhark run 1.fut" with Futhark 0.22.0, I get the output:
```
[43u8, 50u8]
306.000000f64
8i64
-----
trace: 1i64
trace: 3i64
[43u8, 50u8]
0.0f64
8i64
```
The command first compiles and run the compiled program, and then runs the same program with the interpreter. The program is a minimax implementation of a game where the game state is just a number. The three lines it outputs are the best move, the evaluation, and the number of leaves in the move tree. We can see that it finds two different evaluations for the same program. The evaluation of 0 is the correct one.

**Comment by athas** [comment] 2022-11-03 21:10
I cannot reproduce this problem.  Exactly which compiler version are you using?  0.22.0 is just a placeholder version for a prerelease.

**Comment by capt-glorypants** [comment] 2022-11-06 09:26
```
> futhark --version
Futhark 0.22.0
git: 68a4fd9466d4440c9774f347c11c1060d07b11db
[...]
```

**Comment by athas** [comment] 2022-11-06 09:32
I cannot reproduce, but the compiler used is old, so this is probably fixed now.

**Closed by athas** 2022-11-06 09:32 UTC
